---
- name: Configure web server(s)
  hosts: webservers
  sudo: true
  vars:
  - docroot: "/var/www/html/developer.rackspace.com"
  roles:
    - webservers
    - { role: bennojoy.nginx,
        nginx_http_params: { 
          sendfile: "on",
          access_log: "/var/log/nginx/access.log"
        },
        nginx_sites: [
          {
            server: {
              file_name: developer.rackspace.com,
              listen: 80,
              server_name: "{{ server_name }}",
              root: "{{ docroot }}"
            }
          }
        ]
      }
